### ISSUE TITLE
Feature Request: Add littlefs for ESP32

### ISSUE THREAD

**Issue by Jason2866** [maxgerhardt/pio-esp32-esp8266-filesystem-downloader#1]
Great addon! It would be great if you add littlefs for ESP32. We use it for ESP32 already. See [Tasmota](https://github.com/arendst/Tasmota)

**Comment by maxgerhardt** [comment]
Closing as accidental duplicate of #2? ^^

**Comment by Jason2866** [comment]
Sorry, i had problems with my inet connection.
